using System;
using System.Collections.Generic;
using System.Text;

namespace ReflectORM.Core
{
    /// <summary>
    /// Contains event data associated with a Database error
    /// </summary>
    public class DatabaseErrorEventArgs : EventArgs
    {
        private string _strErrorMessage;
        private DatabaseErrorType _type;

        /// <summary>
        /// Provides event data associated with the generated error.
        /// </summary>
        /// <param name="ErrorMessage">The error message generated by the Database Exception.</param>
        /// <param name="ErrorType">The type of error generated.</param>
        public DatabaseErrorEventArgs(string ErrorMessage, DatabaseErrorType ErrorType)
        {
            _strErrorMessage = ErrorMessage;
            _type = ErrorType;
        }

        /// <summary>
        /// Provides event data associated with the generated error.
        /// </summary>
        /// <param name="ex">The exception generated by the error.</param>
        public DatabaseErrorEventArgs(Exception ex)
            : this(ex.ToString(), DatabaseErrorType.Manageble)
        {
        }

        /// <summary>
        /// The type of error associated with this event argument.
        /// </summary>
        public DatabaseErrorType ErrorType
        {
            get { return _type; }
        }

        /// <summary>
        /// The error message generated by the exception
        /// </summary>
        public string ErrorMessage
        {
            get { return _strErrorMessage; }
        }
    }
}
